# DATACENTER-2 / DAR-9 — state on SUBSTRATE-V2: the http backend talks to the
# etcd-backed state service (automation/state-backend/), so farm state + its lock
# live in the mesh-replicated etcd store, not a single host's local file. Any
# leader-eligible node can plan/apply against the same state, with locking.
# No-fixed-center IaC.
#
# DAR-9: the backend ADDRESS is NOT a literal here. OpenTofu backend blocks cannot
# interpolate variables, so the per-mesh host (the control VM overlay IP, or the
# founder lighthouse during Phase A) is supplied at init time via
# `-backend-config=xen-xapi.backend.hcl` (generated by gen-backend-config.sh,
# gitignored). This block keeps only the static lock/unlock methods so no dead
# LAN-node literal lives in a tracked .tf.
#
#   tofu -chdir=infra/tofu/xen-xapi init -backend-config=xen-xapi.backend.hcl
terraform {
  backend "http" {
    lock_method   = "LOCK"
    unlock_method = "UNLOCK"
  }
}
