# DAR-9b — edgeos joins the SUBSTRATE-V2 etcd state plane.
#
# edgeos was LOCAL state (terraform.tfstate on disk, gitignored), which meant DR
# could not capture it and the generator/orchestrator could not treat all four
# roots uniformly. This block moves edgeos onto the same etcd-backed http backend
# as xen-xapi / zone1-do, keyed at /tofu/state/edgeos.
#
# DAR-9: the backend ADDRESS is NOT a literal (OpenTofu backend blocks can't
# interpolate vars). The per-mesh host is supplied at init via
# `-backend-config=edgeos.backend.hcl` (generated by gen-backend-config.sh,
# gitignored) so no dead LAN-node literal lives in a tracked .tf.
#
# LIVE MIGRATION IS GATED. Adding this block does NOT move the on-disk state by
# itself — run automation/state-backend/migrate-edgeos-state.sh (operator, in a
# maintenance window) for the one-time local→etcd migration with a 0-add/0-destroy
# parity gate. See that script + infra/tofu/edgeos/README.md.
#
#   tofu -chdir=infra/tofu/edgeos init -backend-config=edgeos.backend.hcl -migrate-state
terraform {
  backend "http" {
    lock_method   = "LOCK"
    unlock_method = "UNLOCK"
  }
}
