//! Keybinds applier — v2.0.0 Phase C.8.
//!
//! Renders the binding map into a sway-format include file at
//! `$XDG_CONFIG_HOME/sway/config.d/mackes-bindings.conf` (or
//! `~/.config/sway/config.d/...` when the env var is unset). Sway
//! re-reads its include chain on every `swaymsg reload`; mde-session
//! handles the reload kick once the value file is written. For the
//! current X11 + i3 v1.x line the same file shape lives at
//! `~/.config/i3/config.d/mackes-bindings.conf`; we write both so
//! the operator can switch compositors without losing customizations.
//!
//! Default bindings live in `data/sway/config.d/mackes-defaults.conf`
//! + `data/i3/config.d/mackes-defaults.conf`; user overrides win
//! lexicographically because the include directive sorts.

use std::collections::BTreeMap;
use std::path::PathBuf;

use serde::{Deserialize, Serialize};

use super::{SettingKey, SettingValue};

/// JSON payload for `KeybindsMap`: `{"Mod4+q": "exec kill", ...}`.
/// `BTreeMap` for deterministic on-disk ordering.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct KeybindsMap {
    /// `binding-spec` → `exec command`.
    pub bindings: BTreeMap<String, String>,
}

fn config_root() -> PathBuf {
    if let Ok(s) = std::env::var("XDG_CONFIG_HOME") {
        if !s.is_empty() {
            return PathBuf::from(s);
        }
    }
    if let Some(home) = dirs::home_dir() {
        return home.join(".config");
    }
    PathBuf::from(".")
}

/// Path of the sway-format bindings include file.
#[must_use]
pub fn sway_bindings_path() -> PathBuf {
    config_root()
        .join("sway")
        .join("config.d")
        .join("mackes-bindings.conf")
}

/// Path of the i3-format bindings include file (for the v1.x line).
#[must_use]
pub fn i3_bindings_path() -> PathBuf {
    config_root()
        .join("i3")
        .join("config.d")
        .join("mackes-bindings.conf")
}

/// Pure helper: render the bindings map into sway/i3 config syntax.
/// Each line is `bindsym <key> <command>`. Sorted by key for
/// deterministic output (matters for snapshot tests + diffs).
#[must_use]
pub fn render_bindings_conf(map: &KeybindsMap) -> String {
    let mut out = String::new();
    out.push_str("# Generated by mde Phase C.8 — DO NOT EDIT.\n");
    out.push_str("# Source of truth is the org.mackes.MDE.Settings\n");
    out.push_str("# `keybinds.map` key; user edits made here will be\n");
    out.push_str("# overwritten on the next apply.\n");
    out.push_str("\n");
    for (key, cmd) in &map.bindings {
        out.push_str(&format!("bindsym {key} {cmd}\n"));
    }
    out
}

/// Apply a `keybinds.*` setting.
///
/// # Errors
/// Returns an error when the key isn't a keybinds key, the value
/// doesn't deserialize, or the filesystem write fails.
pub fn apply(key: SettingKey, value: &SettingValue) -> anyhow::Result<()> {
    if !matches!(key, SettingKey::KeybindsMap) {
        anyhow::bail!("keybinds: {key} is not a keybinds key");
    }
    let map: KeybindsMap = value.to_serde()?;
    let text = render_bindings_conf(&map);
    for path in [sway_bindings_path(), i3_bindings_path()] {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)
                .map_err(|e| anyhow::anyhow!("keybinds: mkdir {} failed: {e}", parent.display()))?;
        }
        std::fs::write(&path, &text)
            .map_err(|e| anyhow::anyhow!("keybinds: write {} failed: {e}", path.display()))?;
    }
    Ok(())
}

/// Read the current `keybinds.*` setting by parsing the sway file.
///
/// # Errors
/// Returns an error when the key isn't a keybinds key.
pub fn current(key: SettingKey) -> anyhow::Result<SettingValue> {
    if !matches!(key, SettingKey::KeybindsMap) {
        anyhow::bail!("keybinds: {key} is not a keybinds key");
    }
    let mut bindings = BTreeMap::new();
    if let Ok(text) = std::fs::read_to_string(sway_bindings_path()) {
        for line in text.lines() {
            if let Some(rest) = line.trim().strip_prefix("bindsym ") {
                if let Some((k, v)) = rest.split_once(' ') {
                    bindings.insert(k.to_owned(), v.to_owned());
                }
            }
        }
    }
    SettingValue::from_serde(&KeybindsMap { bindings })
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::{Mutex, OnceLock};
    static ENV_LOCK: OnceLock<Mutex<()>> = OnceLock::new();
    fn with_xdg<R>(tmp: &std::path::Path, body: impl FnOnce() -> R) -> R {
        let lock = ENV_LOCK.get_or_init(|| Mutex::new(()));
        let _g = lock.lock().unwrap_or_else(|e| e.into_inner());
        let prev = std::env::var_os("XDG_CONFIG_HOME");
        std::env::set_var("XDG_CONFIG_HOME", tmp);
        let r = body();
        match prev {
            Some(v) => std::env::set_var("XDG_CONFIG_HOME", v),
            None => std::env::remove_var("XDG_CONFIG_HOME"),
        }
        r
    }

    fn make_map() -> KeybindsMap {
        let mut bindings = BTreeMap::new();
        bindings.insert("Mod4+q".into(), "kill".into());
        bindings.insert("Mod4+Return".into(), "exec foot".into());
        KeybindsMap { bindings }
    }

    #[test]
    fn render_bindings_conf_emits_bindsym_per_entry() {
        let text = render_bindings_conf(&make_map());
        assert!(text.contains("bindsym Mod4+q kill"));
        assert!(text.contains("bindsym Mod4+Return exec foot"));
    }

    #[test]
    fn render_bindings_conf_emits_do_not_edit_header() {
        let text = render_bindings_conf(&KeybindsMap::default());
        assert!(text.contains("DO NOT EDIT"));
    }

    #[test]
    fn render_bindings_conf_orders_bindings_alphabetically() {
        let text = render_bindings_conf(&make_map());
        let pos_r = text.find("Mod4+Return").unwrap();
        let pos_q = text.find("Mod4+q").unwrap();
        assert!(pos_r < pos_q, "BTreeMap should sort R before q");
    }

    #[test]
    fn apply_writes_both_sway_and_i3_files() {
        let tmp = tempfile::tempdir().unwrap();
        with_xdg(tmp.path(), || {
            let map = make_map();
            apply(
                SettingKey::KeybindsMap,
                &SettingValue::from_serde(&map).unwrap(),
            )
            .unwrap();
            assert!(sway_bindings_path().is_file(), "sway file must be written");
            assert!(i3_bindings_path().is_file(), "i3 file must be written");
        });
    }

    #[test]
    fn apply_then_current_round_trips_through_sway_parse() {
        let tmp = tempfile::tempdir().unwrap();
        with_xdg(tmp.path(), || {
            apply(
                SettingKey::KeybindsMap,
                &SettingValue::from_serde(&make_map()).unwrap(),
            )
            .unwrap();
            let v = current(SettingKey::KeybindsMap).unwrap();
            let parsed: KeybindsMap = v.to_serde().unwrap();
            assert_eq!(parsed.bindings.get("Mod4+q").unwrap(), "kill");
            assert_eq!(parsed.bindings.get("Mod4+Return").unwrap(), "exec foot");
        });
    }

    #[test]
    fn current_returns_empty_when_no_file() {
        let tmp = tempfile::tempdir().unwrap();
        with_xdg(tmp.path(), || {
            let v = current(SettingKey::KeybindsMap).unwrap();
            let parsed: KeybindsMap = v.to_serde().unwrap();
            assert!(parsed.bindings.is_empty());
        });
    }

    #[test]
    fn apply_rejects_non_keybinds_key() {
        let v = SettingValue::from_serde(&KeybindsMap::default()).unwrap();
        assert!(apply(SettingKey::ThemeName, &v).is_err());
    }
}
