# DATACENTER-2 / DAR-9 — DO zone state on SUBSTRATE-V2 (etcd-backed http backend),
# same as the Xen farm. Separate state key (/state/zone1-do) — zones stay
# independent.
#
# DAR-9: the backend ADDRESS is NOT a literal here (OpenTofu backend blocks can't
# interpolate vars). The per-mesh host is supplied at init via
# `-backend-config=zone1-do.backend.hcl` (generated by gen-backend-config.sh,
# gitignored), so no dead LAN-node literal lives in a tracked .tf.
#
#   tofu -chdir=infra/tofu/zone1-do init -backend-config=zone1-do.backend.hcl
terraform {
  backend "http" {
    lock_method   = "LOCK"
    unlock_method = "UNLOCK"
  }
}
