//! ONBOARD-2 — the lighthouse `/enroll` rustls HTTPS listener.
//!
//! Binds a dedicated TLS listener (default `:4243`) on a node that is
//! `am_lighthouse`, accepts one HTTP request per connection, and
//! routes `POST /enroll` to the pure handler in
//! [`crate::nebula_enroll_endpoint`]. This is the network bootstrap
//! that fixes MESH-1: a NAT'd / remote peer POSTs its CSR here and
//! gets back a signed nebula bundle over the public internet, authed
//! by the single-use join-token bearer — no QNM-Shared pre-mount.
//!
//! Trust model: the endpoint serves a **self-signed** identity whose
//! SHA-256 fingerprint is pinned into every minted join token
//! (ONBOARD-1). The peer verifies that fingerprint before sending its
//! CSR (ONBOARD-3), so there's no trust-on-first-use MITM window and
//! no CA-chain dependency at enroll time.
//!
//! Runtime reachability mirrors the NF-1.5 covert listener: a
//! peer-role box has no endpoint cert, so `build_acceptor` fails, the
//! worker logs at warn + exits, and the supervisor's OnFailure policy
//! backs off. On a lighthouse with the cert present it serves enrolls.
//!
//! §1: Nebula-native control plane — no Tailscale / Headscale / DERP.
//! §3: rustls + ring provider, TLS 1.2/1.3.

#![cfg(feature = "async-services")]

use std::net::SocketAddr;
use std::path::PathBuf;
use std::sync::Arc;
use std::time::Duration;

use rustls::pki_types::pem::PemObject;
use rustls::pki_types::{CertificateDer, PrivateKeyDer};
use tokio::io::{AsyncReadExt, AsyncWriteExt};
use tokio::net::TcpListener;
use tokio_rustls::TlsAcceptor;

use crate::ca::bundle::LighthouseEntry;
use crate::ca::NebulaCertBackend;
use crate::nebula_enroll::SignCsrPaths;
use crate::nebula_enroll_endpoint::{
    handle_enroll, parse_request, HttpResponse, ParseOutcome, DEFAULT_ENROLL_PORT, MAX_ENROLL_BODY,
};

use super::{ShutdownToken, Worker};

/// Default endpoint cert/key — generated by `found` (ONBOARD-4) and
/// persisted alongside the Nebula files. Distinct from the covert
/// tunnel's `lighthouse.crt` so the two TLS identities don't collide.
pub const DEFAULT_CERT_PATH: &str = "/etc/nebula/enroll-endpoint.crt";
/// Default endpoint key path paired with [`DEFAULT_CERT_PATH`].
pub const DEFAULT_KEY_PATH: &str = "/etc/nebula/enroll-endpoint.key";

/// Conventional first-host overlay IP the lighthouse advertises.
/// Matches the csr-watcher + CLI defaults.
const LIGHTHOUSE_OVERLAY_IP: &str = "10.42.0.1";

/// Whole-connection budget — TLS handshake + request read + response
/// write. Bounds slowloris without hurting a real one-shot enroll.
const CONNECTION_TIMEOUT: Duration = Duration::from_secs(15);

/// Accept-loop back-off when a single accept fails — keeps the
/// listener from spinning on a hostile TCP/4243 flood.
const ACCEPT_BACKOFF: Duration = Duration::from_millis(500);

/// Per-connection plumbing the spawned task needs. Cheap to clone
/// (Arc + small owned strings/paths).
#[derive(Clone)]
struct EnrollContext {
    backend: Arc<dyn NebulaCertBackend>,
    db_path: PathBuf,
    workgroup_root: PathBuf,
    paths: SignCsrPaths,
    local_node_id: String,
    external_addr: String,
}

impl EnrollContext {
    fn roster(&self) -> Vec<LighthouseEntry> {
        vec![LighthouseEntry {
            node_id: self.local_node_id.clone(),
            overlay_ip: LIGHTHOUSE_OVERLAY_IP.to_string(),
            external_addr: self.external_addr.clone(),
        }]
    }
}

/// The `/enroll` listener worker.
pub struct NebulaEnrollListener {
    bind_addr: SocketAddr,
    cert_path: PathBuf,
    key_path: PathBuf,
    ctx: EnrollContext,
}

impl NebulaEnrollListener {
    /// Construct with the lighthouse's signing config. `external_addr`
    /// is the lighthouse's public-internet `ip:port` (what the signed
    /// bundle advertises so the peer dials the public addr — closes
    /// the MESH-2 class of static_host_map bug).
    #[must_use]
    pub fn new(
        backend: Arc<dyn NebulaCertBackend>,
        db_path: PathBuf,
        workgroup_root: PathBuf,
        paths: SignCsrPaths,
        local_node_id: String,
        external_addr: String,
    ) -> Self {
        let bind_addr = SocketAddr::from(([0, 0, 0, 0], DEFAULT_ENROLL_PORT));
        Self {
            bind_addr,
            cert_path: PathBuf::from(DEFAULT_CERT_PATH),
            key_path: PathBuf::from(DEFAULT_KEY_PATH),
            ctx: EnrollContext {
                backend,
                db_path,
                workgroup_root,
                paths,
                local_node_id,
                external_addr,
            },
        }
    }

    /// Override the bind address (tests bind `127.0.0.1:0`).
    #[must_use]
    pub fn with_bind_addr(mut self, addr: SocketAddr) -> Self {
        self.bind_addr = addr;
        self
    }

    /// Override the endpoint cert path.
    #[must_use]
    pub fn with_cert(mut self, path: PathBuf) -> Self {
        self.cert_path = path;
        self
    }

    /// Override the endpoint key path.
    #[must_use]
    pub fn with_key(mut self, path: PathBuf) -> Self {
        self.key_path = path;
        self
    }
}

#[async_trait::async_trait]
impl Worker for NebulaEnrollListener {
    fn name(&self) -> &'static str {
        "nebula-enroll-listener"
    }

    async fn run(&mut self, mut shutdown: ShutdownToken) -> anyhow::Result<()> {
        let acceptor = match build_acceptor(&self.cert_path, &self.key_path) {
            Ok(a) => a,
            Err(e) => {
                // No endpoint cert (peer-role box) or unreadable key:
                // warn + exit, supervisor backs off. Same posture as
                // the NF-1.5 covert listener.
                tracing::warn!(
                    cert = %self.cert_path.display(),
                    error = %e,
                    "nebula-enroll-listener: cert load failed; worker exiting",
                );
                return Err(anyhow::anyhow!("cert load: {e}"));
            }
        };
        let listener = match TcpListener::bind(self.bind_addr).await {
            Ok(l) => l,
            Err(e) => {
                tracing::warn!(
                    bind = %self.bind_addr,
                    error = %e,
                    "nebula-enroll-listener: bind failed; worker exiting",
                );
                return Err(anyhow::anyhow!("bind: {e}"));
            }
        };
        tracing::info!(
            bind = %self.bind_addr,
            "nebula-enroll-listener: accepting peer enrollments",
        );

        loop {
            tokio::select! {
                _ = shutdown.wait() => {
                    tracing::info!("nebula-enroll-listener: shutdown requested");
                    return Ok(());
                }
                accept = listener.accept() => {
                    match accept {
                        Ok((tcp, peer)) => {
                            let acceptor = acceptor.clone();
                            let ctx = self.ctx.clone();
                            tokio::spawn(async move {
                                let outcome = tokio::time::timeout(
                                    CONNECTION_TIMEOUT,
                                    serve_connection(acceptor, tcp, ctx),
                                )
                                .await;
                                match outcome {
                                    Ok(Ok(())) => {}
                                    Ok(Err(e)) => tracing::debug!(
                                        %peer, error = %e,
                                        "nebula-enroll-listener: connection error",
                                    ),
                                    Err(_) => tracing::debug!(
                                        %peer,
                                        "nebula-enroll-listener: connection timed out",
                                    ),
                                }
                            });
                        }
                        Err(e) => {
                            tracing::debug!(
                                error = %e,
                                "nebula-enroll-listener: accept failed; backing off",
                            );
                            tokio::time::sleep(ACCEPT_BACKOFF).await;
                        }
                    }
                }
            }
        }
    }
}

/// Build a TLS 1.2/1.3 acceptor from the endpoint PEM cert + key.
/// Pure once the files are read; returns a `String` error so the
/// worker can warn-and-exit uniformly.
fn build_acceptor(
    cert_path: &std::path::Path,
    key_path: &std::path::Path,
) -> Result<TlsAcceptor, String> {
    let cert_pem =
        std::fs::read(cert_path).map_err(|e| format!("read {}: {e}", cert_path.display()))?;
    let key_pem =
        std::fs::read(key_path).map_err(|e| format!("read {}: {e}", key_path.display()))?;
    let cert_chain: Vec<CertificateDer<'static>> = CertificateDer::pem_slice_iter(&cert_pem)
        .collect::<Result<Vec<_>, _>>()
        .map_err(|e| format!("parse cert pem: {e}"))?;
    if cert_chain.is_empty() {
        return Err(format!("no certs in {}", cert_path.display()));
    }
    let key: PrivateKeyDer<'static> =
        PrivateKeyDer::from_pem_slice(&key_pem).map_err(|e| format!("parse key pem: {e}"))?;
    let provider = Arc::new(rustls::crypto::ring::default_provider());
    let config = rustls::ServerConfig::builder_with_provider(provider)
        .with_safe_default_protocol_versions()
        .map_err(|e| format!("protocol versions: {e}"))?
        .with_no_client_auth()
        .with_single_cert(cert_chain, key)
        .map_err(|e| format!("server config: {e}"))?;
    Ok(TlsAcceptor::from(Arc::new(config)))
}

/// Handle exactly one TLS connection: handshake, read one HTTP
/// request, dispatch, write the response, close.
async fn serve_connection(
    acceptor: TlsAcceptor,
    tcp: tokio::net::TcpStream,
    ctx: EnrollContext,
) -> anyhow::Result<()> {
    let mut tls = acceptor.accept(tcp).await?;
    // Read until parse_request yields a verdict. Cap the buffer at the
    // body cap + header slack so a peer can't exhaust memory.
    let max_buf = MAX_ENROLL_BODY + 8 * 1024;
    let mut buf: Vec<u8> = Vec::with_capacity(4096);
    let mut chunk = [0_u8; 4096];
    let response = loop {
        match parse_request(&buf) {
            ParseOutcome::Complete(req) => break dispatch(req, &ctx).await,
            ParseOutcome::Invalid(why) => {
                break HttpResponse {
                    status: 400,
                    body: error_json(why),
                }
            }
            ParseOutcome::NeedMore => {}
        }
        if buf.len() >= max_buf {
            break HttpResponse {
                status: 400,
                body: error_json("request too large"),
            };
        }
        let n = tls.read(&mut chunk).await?;
        if n == 0 {
            // EOF before a complete request.
            break HttpResponse {
                status: 400,
                body: error_json("incomplete request"),
            };
        }
        buf.extend_from_slice(&chunk[..n]);
    };
    tls.write_all(&response.to_wire()).await?;
    tls.flush().await?;
    let _ = tls.shutdown().await;
    Ok(())
}

/// Route a parsed request. Only `POST /enroll` is real; everything
/// else gets a terse status. The signing call shells out to
/// nebula-cert + touches SQLite, so it runs on the blocking pool.
async fn dispatch(
    req: crate::nebula_enroll_endpoint::HttpRequest,
    ctx: &EnrollContext,
) -> HttpResponse {
    if req.path != "/enroll" {
        return HttpResponse {
            status: 404,
            body: error_json("not found"),
        };
    }
    if req.method != "POST" {
        return HttpResponse {
            status: 405,
            body: error_json("method not allowed"),
        };
    }
    let ctx = ctx.clone();
    let body = req.body;
    let join = tokio::task::spawn_blocking(move || {
        handle_enroll(
            &*ctx.backend,
            &ctx.db_path,
            &ctx.workgroup_root,
            &ctx.paths,
            ctx.roster(),
            &body,
        )
    })
    .await;
    match join {
        Ok(resp) => resp,
        Err(e) => {
            tracing::warn!(error = %e, "nebula-enroll-listener: signing task panicked");
            HttpResponse {
                status: 500,
                body: error_json("internal signing error"),
            }
        }
    }
}

fn error_json(message: &str) -> Vec<u8> {
    serde_json::json!({ "error": message })
        .to_string()
        .into_bytes()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ca::{mint, MockBackend};

    fn test_listener(root: &std::path::Path) -> NebulaEnrollListener {
        let db_path = root.join("mackesd.db");
        let conn = crate::store::open(&db_path).expect("open");
        let ca_crt = root.join("ca.crt");
        let ca_key = root.join("ca.key");
        mint::mint_ca(
            &MockBackend,
            &conn,
            "test-mesh",
            Some(&ca_crt),
            Some(&ca_key),
        )
        .expect("mint");
        let paths = SignCsrPaths {
            ca_crt,
            ca_key,
            scratch_dir: root.join("scratch"),
        };
        NebulaEnrollListener::new(
            Arc::new(MockBackend),
            db_path,
            root.to_path_buf(),
            paths,
            "peer:lighthouse-1".into(),
            "203.0.113.7:4242".into(),
        )
    }

    #[test]
    fn worker_name_is_kebab_case() {
        let tmp = tempfile::tempdir().unwrap();
        assert_eq!(test_listener(tmp.path()).name(), "nebula-enroll-listener");
    }

    #[test]
    fn default_bind_is_enroll_port() {
        let tmp = tempfile::tempdir().unwrap();
        assert_eq!(
            test_listener(tmp.path()).bind_addr.port(),
            DEFAULT_ENROLL_PORT
        );
    }

    #[test]
    fn builders_override_each_field() {
        let tmp = tempfile::tempdir().unwrap();
        let addr: SocketAddr = "127.0.0.1:0".parse().unwrap();
        let w = test_listener(tmp.path())
            .with_bind_addr(addr)
            .with_cert(PathBuf::from("/tmp/e.crt"))
            .with_key(PathBuf::from("/tmp/e.key"));
        assert_eq!(w.bind_addr, addr);
        assert_eq!(w.cert_path, PathBuf::from("/tmp/e.crt"));
        assert_eq!(w.key_path, PathBuf::from("/tmp/e.key"));
    }

    #[tokio::test]
    async fn worker_exits_when_cert_missing() {
        let tmp = tempfile::tempdir().unwrap();
        let mut w = test_listener(tmp.path())
            .with_bind_addr("127.0.0.1:0".parse().unwrap())
            .with_cert(PathBuf::from("/nonexistent/e.crt"))
            .with_key(PathBuf::from("/nonexistent/e.key"));
        let (_tx, rx) = tokio::sync::watch::channel(false);
        let token = ShutdownToken::from_receiver(rx);
        let result = w.run(token).await;
        assert!(result.is_err());
        assert!(format!("{:?}", result.unwrap_err())
            .to_lowercase()
            .contains("cert"));
    }

    #[test]
    fn build_acceptor_loads_a_generated_identity() {
        // A freshly-generated endpoint identity must load into a
        // working acceptor (round-trips the ONBOARD-2 cert format).
        let tmp = tempfile::tempdir().unwrap();
        let id = crate::nebula_enroll_endpoint::generate_endpoint_identity(&["127.0.0.1".into()])
            .expect("gen");
        let crt = tmp.path().join("e.crt");
        let key = tmp.path().join("e.key");
        std::fs::write(&crt, id.cert_pem).unwrap();
        std::fs::write(&key, id.key_pem).unwrap();
        assert!(build_acceptor(&crt, &key).is_ok());
    }

    fn roster_ctx(root: &std::path::Path) -> EnrollContext {
        test_listener(root).ctx
    }

    #[test]
    fn roster_advertises_the_public_external_addr() {
        let tmp = tempfile::tempdir().unwrap();
        let r = roster_ctx(tmp.path()).roster();
        assert_eq!(r.len(), 1);
        assert_eq!(r[0].external_addr, "203.0.113.7:4242");
        assert_eq!(r[0].overlay_ip, LIGHTHOUSE_OVERLAY_IP);
    }

    #[tokio::test]
    async fn end_to_end_tls_enroll_returns_bundle() {
        use crate::enrollment::build_identity;
        use crate::nebula_enroll::{build_pending, parse_join_token};
        use rustls::pki_types::ServerName;
        use rustls::RootCertStore;

        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path();
        let ctx = roster_ctx(root);

        // Generate the endpoint identity + a pinning client root store.
        let id = crate::nebula_enroll_endpoint::generate_endpoint_identity(&["localhost".into()])
            .expect("gen");
        let crt = root.join("e.crt");
        let key = root.join("e.key");
        std::fs::write(&crt, &id.cert_pem).unwrap();
        std::fs::write(&key, &id.key_pem).unwrap();
        let acceptor = build_acceptor(&crt, &key).expect("acceptor");

        // Seed an issued bearer + build the CSR body the peer would POST.
        let token = parse_join_token("mesh:test-mesh@10.0.0.5:4243#e2e-bearer").unwrap();
        crate::bearer_ledger::record_issued(root, &token.bearer).unwrap();
        let pending = build_pending(&build_identity(), "peer:anvil", "anvil", token);
        let body = serde_json::to_vec(&pending).unwrap();

        // Bind + serve exactly one connection through the real path.
        let listener = TcpListener::bind("127.0.0.1:0").await.unwrap();
        let addr = listener.local_addr().unwrap();
        let server = tokio::spawn(async move {
            let (tcp, _) = listener.accept().await.unwrap();
            serve_connection(acceptor, tcp, ctx).await
        });

        // Pinning client: trust ONLY the generated cert.
        let mut roots = RootCertStore::empty();
        for cert in CertificateDer::pem_slice_iter(id.cert_pem.as_bytes()) {
            roots.add(cert.unwrap()).unwrap();
        }
        let provider = Arc::new(rustls::crypto::ring::default_provider());
        let client_config = rustls::ClientConfig::builder_with_provider(provider)
            .with_safe_default_protocol_versions()
            .unwrap()
            .with_root_certificates(roots)
            .with_no_client_auth();
        let connector = tokio_rustls::TlsConnector::from(Arc::new(client_config));
        let tcp = tokio::net::TcpStream::connect(addr).await.unwrap();
        let server_name = ServerName::try_from("localhost").unwrap();
        let mut tls = connector
            .connect(server_name, tcp)
            .await
            .expect("tls handshake");

        let request = format!(
            "POST /enroll HTTP/1.1\r\nHost: localhost\r\nContent-Length: {}\r\nConnection: close\r\n\r\n",
            body.len()
        );
        tls.write_all(request.as_bytes()).await.unwrap();
        tls.write_all(&body).await.unwrap();
        tls.flush().await.unwrap();

        let mut resp = Vec::new();
        tls.read_to_end(&mut resp).await.unwrap();
        server.await.unwrap().expect("server ok");

        let text = String::from_utf8_lossy(&resp);
        assert!(
            text.starts_with("HTTP/1.1 200 OK"),
            "got: {}",
            &text[..text.len().min(60)]
        );
        let body_start = text.find("\r\n\r\n").unwrap() + 4;
        let bundle: crate::ca::bundle::NebulaBundle =
            serde_json::from_str(&text[body_start..]).expect("bundle json");
        assert_eq!(bundle.mesh_id, "test-mesh");
        assert_eq!(bundle.lighthouses[0].external_addr, "203.0.113.7:4242");
        // Single-use: the bearer is spent after the network enroll.
        assert!(!crate::bearer_ledger::is_pending(
            root,
            &pending.token.bearer
        ));
    }

    #[tokio::test]
    async fn dispatch_rejects_wrong_route_and_method() {
        let tmp = tempfile::tempdir().unwrap();
        let ctx = roster_ctx(tmp.path());
        let bad_path = crate::nebula_enroll_endpoint::HttpRequest {
            method: "POST".into(),
            path: "/other".into(),
            body: vec![],
        };
        assert_eq!(dispatch(bad_path, &ctx).await.status, 404);
        let bad_method = crate::nebula_enroll_endpoint::HttpRequest {
            method: "GET".into(),
            path: "/enroll".into(),
            body: vec![],
        };
        assert_eq!(dispatch(bad_method, &ctx).await.status, 405);
    }
}
