#!/usr/bin/env bash
# gen-backend-config.sh — DAR-8: generate each Tofu root's backend config from the
# control VM overlay IP, so the state backend comes along with NO hardcoded host.
#
# Tofu backend blocks can't interpolate variables, so the host address lives in a
# generated, GITIGNORED `<root>.backend.hcl` (one per root) passed to `tofu init`
# via `-backend-config=`. The tracked backend.tf in each root keeps only the
# static lock_method/unlock_method (DAR-9). This script is the single producer of
# the address half; infra/tofu/backend.tf.tmpl is the single template source.
#
# Usage:
#   gen-backend-config.sh --control-ip <overlay-ip> [--roots "r1 r2 ..."] \
#                         [--tofu-dir <infra/tofu>] [--node <mesh-node>]
#
# Defaults to the four roots (xen-xapi zone1-do edgeos control-vm). Re-running
# with the same IP is byte-identical (idempotent); a different IP rewrites them.
#
# WL-ARCH-006 U5/U11 — the `cloud` root is PER-NODE: each placement node keeps its
# own state slice so a per-node apply never clobbers a peer's. Pass `--node <node>`
# with `--roots cloud` (or a list containing it) and the cloud root's state key
# becomes `state/cloud/<node>` instead of `state/cloud`. Every other root is
# unchanged (node-agnostic), so existing callers are byte-identical.
set -euo pipefail

CONTROL_IP=""
ROOTS="xen-xapi zone1-do edgeos control-vm"
NODE=""
HERE="$(cd "$(dirname "$0")" && pwd)"
TOFU_DIR="$(cd "$HERE/../.." && pwd)/infra/tofu"

while [ $# -gt 0 ]; do case "$1" in
  --control-ip) CONTROL_IP="$2"; shift 2;;
  --roots)      ROOTS="$2"; shift 2;;
  --tofu-dir)   TOFU_DIR="$2"; shift 2;;
  --node)       NODE="$2"; shift 2;;
  -h|--help)    sed -n '2,26p' "$0" | sed 's/^# \{0,1\}//'; exit 0;;
  *) echo "gen-backend-config: unknown arg: $1" >&2; exit 1;;
esac; done

if [ -z "$CONTROL_IP" ]; then
  echo "gen-backend-config: --control-ip <overlay-ip> is required" >&2
  exit 1
fi
# Reject the dead LAN node as a host (it is never a valid generated target except
# for the explicit byte-for-byte reconstitute arm, which the operator runs knowing
# this; warn but do not block — DAR-17 says =172.20.145.192 reproduces today).
case "$CONTROL_IP" in
  172.20.145.192) echo "gen-backend-config: WARNING --control-ip is the dead LAN node 172.20.145.192 (reconstitute-arm only)" >&2;;
esac

TMPL="$TOFU_DIR/backend.tf.tmpl"
[ -r "$TMPL" ] || { echo "gen-backend-config: missing template $TMPL" >&2; exit 1; }

for root in $ROOTS; do
  rootdir="$TOFU_DIR/$root"
  if [ ! -d "$rootdir" ]; then
    echo "gen-backend-config: skip $root (no $rootdir)" >&2
    continue
  fi
  out="$rootdir/$root.backend.hcl"
  # The cloud root is per-node (WL-ARCH-006): its state key carries the placement
  # node so a per-node apply owns only its own slice. Every other root keeps its
  # flat, node-agnostic key.
  statepath="$root"
  if [ "$root" = "cloud" ] && [ -n "$NODE" ]; then
    statepath="cloud/$NODE"
  fi
  # The -backend-config HCL is the body of the http backend block (no wrapper).
  cat > "$out" <<EOF
# GENERATED by gen-backend-config.sh — do not edit, do not commit.
# control-ip: $CONTROL_IP   root: $root   state-key: $statepath
address        = "http://$CONTROL_IP:8390/state/$statepath"
lock_address   = "http://$CONTROL_IP:8390/state/$statepath"
unlock_address = "http://$CONTROL_IP:8390/state/$statepath"
lock_method    = "LOCK"
unlock_method  = "UNLOCK"
EOF
  echo "wrote $out"

  # All four roots carry a TRACKED, literal-free backend.tf (only lock methods);
  # the address comes from the generated .backend.hcl above. edgeos's tracked
  # backend.tf is added by DAR-9b so it joins the etcd state plane (it was LOCAL
  # state). If a root is somehow missing its tracked backend.tf, render the
  # literal-free skeleton from the template (drop the address lines) so init can
  # still find an http backend.
  if [ ! -f "$rootdir/backend.tf" ]; then
    grep -v -E '^\s*(address|lock_address|unlock_address)\s*=' "$TMPL" \
      | sed -e "s|__ROOT__|$root|g" > "$rootdir/backend.tf"
    echo "wrote $rootdir/backend.tf (literal-free skeleton)"
  fi
done
