# WL-ARCH-001 Phase B — the cloud root joins the SUBSTRATE-V2 etcd state plane,
# keyed at /tofu/state/cloud, exactly like xen-xapi / zone1-do / edgeos. So DR
# captures it and the generator/orchestrator treat every root uniformly.
#
# The backend ADDRESS is NOT a literal (OpenTofu backend blocks can't interpolate
# vars). The per-mesh host is supplied at init via
# `-backend-config=cloud.backend.hcl` (generated by
# automation/state-backend/gen-backend-config.sh, gitignored) so no dead LAN-node
# literal lives in a tracked .tf. State + lock keys live under the FROZEN
# /tofu/state/* + /tofu/lock/* prefixes served by
# automation/state-backend/tofu-state-etcd.py.
#
# Init against etcd:   tofu init -backend-config=cloud.backend.hcl
# Init offline (CI):   tofu init -backend=false   (validate / fmt only — no state)
terraform {
  backend "http" {
    lock_method   = "LOCK"
    unlock_method = "UNLOCK"
  }
}
