# WL-ARCH-001 Phase B + WL-ARCH-006 U5/U11 — the cloud root joins the SUBSTRATE-V2
# etcd state plane, keyed under /tofu/state/cloud, exactly like xen-xapi / zone1-do
# / edgeos. So DR captures it and the generator/orchestrator treat every root
# uniformly.
#
# PER-NODE STATE: the cloud root is placement-node-scoped — each node keeps its own
# slice at `state/cloud/<node>` so a per-node apply (the mackesd cloud worker on
# node N renders + applies only N's workloads) never clobbers a peer's. The node
# suffix is baked into the generated `cloud.backend.hcl` by
# `gen-backend-config.sh --roots cloud --node <node>` (a bare `state/cloud` when no
# node is given, for a single-node dev box).
#
# The backend ADDRESS is NOT a literal (OpenTofu backend blocks can't interpolate
# vars). The per-mesh host + per-node key are supplied at init via
# `-backend-config=cloud.backend.hcl` (generated by
# automation/state-backend/gen-backend-config.sh, gitignored) so no dead LAN-node
# literal lives in a tracked .tf. State + lock keys live under the FROZEN
# /tofu/state/* + /tofu/lock/* prefixes served by
# automation/state-backend/tofu-state-etcd.py.
#
# Init against etcd:   tofu init -backend-config=cloud.backend.hcl
# Init offline (CI):   tofu init -backend=false   (validate / fmt only — no state)
terraform {
  backend "http" {
    lock_method   = "LOCK"
    unlock_method = "UNLOCK"
  }
}
