//! Per-panel views — one module per group leaf. CB-1.x ports
//! land these incrementally; each module ships a state struct,
//! a `Message` variant set, an `update` reducer that returns
//! the parent app's `Message`, and a `view` builder over
//! [`Element<'_, crate::Message>`].

pub mod about;
pub mod apps_install;
pub mod apps_installed;
pub mod apps_remove;
pub mod apps_sources;
pub mod audit;
pub mod compute;
pub mod config_apply;
pub mod connect;
pub mod datetime;
pub mod default_apps;
pub mod displays;
pub mod dns;
pub mod drift;
pub mod firewall;
pub mod fleet_logs;
pub mod fleet_revisions;
pub mod fleet_rollup;
pub mod fleet_settings;
pub mod fonts;
pub mod hardware;
pub mod health_check;
pub mod help_index;
pub mod home;
pub mod hub;
pub mod images;
pub mod interfaces;
pub mod inventory;
pub mod jobs;
pub mod json_helpers;
pub mod keyboard;
pub mod logs;
pub mod mesh_bus;
pub mod mesh_control;
pub mod mesh_federation;
pub mod mesh_history;
pub mod mesh_join;
pub mod mesh_logs;
pub mod mesh_pending;
pub mod mesh_services;
pub mod mesh_storage;
pub mod node_roster;
pub mod mirrors;
pub mod mouse;
pub mod music;
pub mod network_hosts;
pub mod node_roles;
pub mod notifications;
pub mod panel_apps;
/// PD-3 — the Peers directory (the Front Door).
pub mod peers;
/// PD-7 — the live mesh map (the Peers panel's Map view).
pub mod peers_map;
pub mod playbooks;
pub mod policy;
pub mod power;
pub mod printers;
pub mod profiles;
pub mod registration;
pub mod remote_desktop;
pub mod removable;
pub mod repair;
pub mod resources;
pub mod routing;
pub mod run_history;
pub mod service_publishing;
pub mod session;
pub mod snapshots;
pub mod sound;
pub mod sparkline;
pub mod sync_status;
pub mod system_update;
pub mod tags;
pub mod themes;
pub mod vm_wizard;
pub mod vpn;
pub mod wallpaper;
pub mod wifi;
