//! SETUP-7 — the `/etc/mackesd/site.yml` convergence playbook emitter.
//!
//! The hybrid config model (design lock 3): the imperative verbs (`found`/
//! `join`/`setup-etcd`/`setup-syncthing`) bootstrap a node interactively, then
//! emit this self-contained Ansible playbook capturing the resulting facts (role,
//! mesh-id, lighthouse roster, shared-storage path, the boot-durable service
//! set). Re-applying
//! it (`mackesd converge`, or the `ansible-pull` worker) idempotently restores
//! steady state — every later config change goes through it, not ad-hoc edits.
//!
//! The playbook applies the shipped `mackes` role
//! (`/usr/share/mackes/ansible/roles/mackes`). Rendering is pure (no I/O) so the
//! exact YAML is unit-tested; [`write_site_yml`] is the thin file wrapper.

use std::io;
use std::path::Path;

/// Default path for the generated convergence playbook.
pub const DEFAULT_SITE_YML: &str = "/etc/mackesd/site.yml";

/// The boot-durable service set the `mackes` role guarantees enabled + running
/// (mirrors the ONBOARD-9 manager + the SETUP design "Service set"). Role-gated
/// units (the leader-only services on the founder) layer on via the role's own tasks.
pub const CONVERGE_SERVICES: [&str; 5] = [
    "nebula.service",
    "mackesd.service",
    "mesh-health.timer",
    "etcd.service",
    "syncthing.service",
];

/// The node facts a converge run needs — captured from the bootstrap result.
#[derive(Debug, Clone)]
pub struct SiteFacts {
    /// Pinned deployment role (`lighthouse`/`server`/`workstation`).
    pub role: String,
    /// Mesh id this node belongs to.
    pub mesh_id: String,
    /// Lighthouse overlay IPs (the roster; peers point at all of them).
    pub lighthouses: Vec<String>,
    /// QNM-Shared mount path (`/mnt/mesh-storage`).
    pub qnm_path: String,
    /// The service set to keep enabled + running.
    pub services: Vec<String>,
}

impl SiteFacts {
    /// Build facts with the standard service set for a node.
    #[must_use]
    pub fn new(role: &str, mesh_id: &str, lighthouses: Vec<String>, qnm_path: &str) -> Self {
        Self {
            role: role.to_owned(),
            mesh_id: mesh_id.to_owned(),
            lighthouses,
            qnm_path: qnm_path.to_owned(),
            services: CONVERGE_SERVICES.iter().map(|s| (*s).to_owned()).collect(),
        }
    }
}

/// Render the convergence playbook YAML for `facts`. Pure. The values are
/// platform-controlled (url-safe mesh-id, IP rosters, fixed service names), so a
/// flat hand-render is safe + dependency-free; each list item is quoted.
#[must_use]
pub fn render(facts: &SiteFacts) -> String {
    let mut out = String::new();
    out.push_str("# /etc/mackesd/site.yml — GENERATED by magic-setup/mackesd (SETUP-7).\n");
    out.push_str("# Steady-state convergence playbook; do not hand-edit.\n");
    out.push_str("# Re-apply: `mackesd converge` (or the ansible-pull worker).\n");
    out.push_str("- hosts: localhost\n");
    out.push_str("  connection: local\n");
    out.push_str("  become: true\n");
    out.push_str("  vars:\n");
    out.push_str(&format!("    mde_role: \"{}\"\n", facts.role));
    out.push_str(&format!("    mde_mesh_id: \"{}\"\n", facts.mesh_id));
    out.push_str(&format!("    mde_qnm_path: \"{}\"\n", facts.qnm_path));
    out.push_str("    mde_lighthouses:\n");
    for lh in &facts.lighthouses {
        out.push_str(&format!("      - \"{lh}\"\n"));
    }
    out.push_str("    mde_services:\n");
    for svc in &facts.services {
        out.push_str(&format!("      - \"{svc}\"\n"));
    }
    out.push_str("  roles:\n");
    out.push_str("    - role: mackes\n");
    out
}

/// Render + write the playbook to `path`, creating the parent dir. Best-effort
/// caller (found/join) — a write failure is logged, not fatal.
///
/// # Errors
/// Returns the underlying [`io::Error`] on a create-dir or write failure.
pub fn write_site_yml(path: &Path, facts: &SiteFacts) -> io::Result<()> {
    if let Some(dir) = path.parent() {
        std::fs::create_dir_all(dir)?;
    }
    std::fs::write(path, render(facts))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn facts() -> SiteFacts {
        SiteFacts::new(
            "workstation",
            "home-mesh",
            vec!["10.42.0.1".to_string(), "10.42.0.2".to_string()],
            "/mnt/mesh-storage",
        )
    }

    #[test]
    fn render_is_valid_looking_playbook_with_the_facts() {
        let y = render(&facts());
        assert!(y.contains("- hosts: localhost"));
        assert!(y.contains("connection: local"));
        assert!(y.contains("mde_role: \"workstation\""));
        assert!(y.contains("mde_mesh_id: \"home-mesh\""));
        assert!(y.contains("mde_qnm_path: \"/mnt/mesh-storage\""));
        assert!(y.contains("- \"10.42.0.1\""));
        assert!(y.contains("- \"10.42.0.2\""));
        assert!(y.contains("- role: mackes"));
    }

    #[test]
    fn render_lists_the_full_service_set() {
        let y = render(&facts());
        for svc in CONVERGE_SERVICES {
            assert!(y.contains(&format!("- \"{svc}\"")), "missing {svc}");
        }
    }

    #[test]
    fn new_populates_the_default_service_set() {
        assert_eq!(facts().services.len(), CONVERGE_SERVICES.len());
    }

    #[test]
    fn write_site_yml_creates_parent_and_file() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("etc/mackesd/site.yml");
        write_site_yml(&path, &facts()).expect("write");
        let body = std::fs::read_to_string(&path).unwrap();
        assert!(body.contains("- role: mackes"));
    }
}
