# WL-ARCH-006 U12 — the service-container module: the Quadlet/Ansible container path
# target.
#
# Unlike the VM/Android modules, tofu does NOT run podman here — the local-first
# decided stack (WL-ARCH-001 #8) installs containers as rootless Quadlet `.container`
# systemd units via Ansible's `container_host` role. This module owns the DECLARATION
# (the desired container spec + the rendered Quadlet unit) so tofu tracks each
# container's create/destroy lifecycle in state; the Ansible role reads the rendered
# unit from the root's `containers` output and installs it. Rootless by default.
#
# Built on `terraform_data` (a built-in resource — no provider), so the module adds
# no cloud dependency and validates/plans offline.

locals {
  rootless = true

  # The mesh network the container joins: its own segment when isolation is
  # requested, else the shared managed mesh network.
  container_network = var.network_isolation ? "${var.name}-net" : var.network_name

  # The rendered rootless Quadlet `.container` unit the container_host role installs
  # (podman reads [Container]; systemd generates the service from [Install]).
  quadlet_unit = <<-UNIT
    # GENERATED by infra/tofu/cloud/modules/container — installed by the Ansible
    # container_host role as a rootless Quadlet unit. Do not edit on the host.
    [Unit]
    Description=MCNF workload container ${var.name}
    After=network-online.target

    [Container]
    ContainerName=${var.name}
    Image=${var.image}
    Network=${local.container_network}
    # Resource caps (the delivery-type shape's vcpu/memory).
    PodmanArgs=--cpus=${var.vcpu} --memory=${var.memory_mb}m

    [Service]
    Restart=always

    [Install]
    WantedBy=default.target
  UNIT
}

# The tracked desired-state of this container — its create/destroy lifecycle rides
# tofu state (add/remove the workload key ⇒ create/destroy), while the actual
# install is the Ansible container_host role's job.
resource "terraform_data" "container" {
  input = {
    name     = var.name
    image    = var.image
    rootless = local.rootless
    network  = local.container_network
  }
}
