#!/usr/bin/env bash
# mcnf-config.sh — DAR-4 (DEVOPS-AUTOMATION-REBUILD §2.3): the per-mesh, NON-SECRET
# identity doc, captured at FOUND time and source-able by every other backoffice
# script.
#
# WHY this exists: the backoffice must be SELF-DESCRIBING — a fresh control VM (or a
# DR reconstitution) needs the mesh's identity (mesh-id, project, regions, the
# control-VM overlay IP, the lighthouse roster, the golden template) WITHOUT any
# hand-edited HCL. So `gen` writes that identity ONCE to etcd as a non-secret doc;
# `render` regenerates the per-root `*.auto.tfvars` purely from the etcd doc on any
# node. The doc holds ZERO credentials — only tokens come from /mcnf/secret/* (the
# secret store, mcnf-secret.sh). This is the seam DAR-33's gen-tfvars.sh composes:
# gen-tfvars sources THIS lib for the identity and adds the backend-config half.
#
# Canonical etcd keys (lock 7, non-secret):
#   /mcnf/backoffice/config        the whole identity as one JSON doc (source of truth)
#   /mcnf/site/mesh-id             flat per-field mirror (so other scripts can range/get
#   /mcnf/site/project             a single field without parsing JSON)
#   /mcnf/site/regions             comma-joined region list
#   /mcnf/site/control-overlay-ip  the control VM overlay IP (state-backend host)
#   /mcnf/site/lighthouses         comma-joined lighthouse overlay IP roster
#   /mcnf/site/domain              the DNS zone (zone1-do)
#   /mcnf/site/golden-template     the canonical golden template name (MDE-VM-golden)
#
# Usage:
#   mcnf-config.sh gen <mesh-id> --project <p> --regions <r,...> --lighthouses <ip,...>
#                  [--control-ip <overlay-ip>] [--domain <zone>] [--golden <name>]
#                  [--tofu-dir <infra/tofu>] [--no-render]
#                                       write the doc to etcd (+ /mcnf/site/*) then render
#   mcnf-config.sh render [--tofu-dir <dir>]
#                                       regenerate *.auto.tfvars purely from the etcd doc
#   mcnf-config.sh get [<field>]        print the JSON doc (or one /mcnf/site/<field>)
#   mcnf-config.sh selftest             offline self-test (mocked etcd; NO live store)
#
# Source-able: `. mcnf-config.sh` defines mcnf_config_get_field / mcnf_config_load
# without running anything (guarded by the ${MCNF_CONFIG_LIB:-} sourcing sentinel).
#
# Env:
#   MCNF_ETCD             etcd v3 HTTP endpoint(s) — resolved by DAR-1b
#                         (automation/lib/etcd-endpoints.sh); NO dead .192 default.
#   MCNF_CONFIG_SELFTEST  set by `selftest` — routes etcd I/O to a local mock dir.
set -euo pipefail

_MCNF_CONFIG_HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=./etcd-endpoints.sh
. "$_MCNF_CONFIG_HERE/etcd-endpoints.sh"

CONFIG_KEY="/mcnf/backoffice/config"
SITE_PREFIX="/mcnf/site"

# ── etcd endpoint resolution (fail-loud; NO dead .192 default — DAR-1b) ──
_cfg_resolve_etcd() {
  if [ -n "${MCNF_CONFIG_SELFTEST:-}" ]; then ETCD="mock://selftest"; return 0; fi
  ETCD="$(mcnf_resolve_etcd_first)" || exit 1
}

_cfg_b64() { base64 -w0; }

# ── etcd v3 HTTP KV (mockable for selftest) ──
_cfg_mock_path() { printf '%s/%s' "$MOCK_DIR" "$(printf %s "$1" | _cfg_b64)"; }

_cfg_put() { # <key> <raw-value>
  if [ "$ETCD" = "mock://selftest" ]; then
    mkdir -p "$MOCK_DIR"; printf %s "$2" >"$(_cfg_mock_path "$1")"; return 0
  fi
  local k v; k=$(printf %s "$1" | _cfg_b64); v=$(printf %s "$2" | _cfg_b64)
  curl -fsS -X POST "$ETCD/v3/kv/put" -d "{\"key\":\"$k\",\"value\":\"$v\"}" >/dev/null
}

_cfg_get() { # <key> -> raw value on stdout (exit 3 if absent)
  if [ "$ETCD" = "mock://selftest" ]; then
    local p; p="$(_cfg_mock_path "$1")"
    [ -f "$p" ] || return 3
    cat "$p"; return 0
  fi
  local k; k=$(printf %s "$1" | _cfg_b64)
  curl -fsS -X POST "$ETCD/v3/kv/range" -d "{\"key\":\"$k\"}" | python3 -c '
import sys, json, base64
d = json.load(sys.stdin); kvs = d.get("kvs")
if not kvs: sys.exit(3)
sys.stdout.buffer.write(base64.b64decode(kvs[0]["value"]))'
}

# ── render: build a root's *.auto.tfvars from the loaded identity fields ──
# Each root gets only the vars it actually declares (we never emit a var a root
# doesn't have, which would make `tofu plan` warn). NEVER writes a credential.
_cfg_render_roots() { # uses the CFG_* globals set by _cfg_load_into_globals
  local tofu_dir="$1"
  local ts; ts="$(date -u +%FT%TZ 2>/dev/null || echo unknown)"
  local hdr="# GENERATED by mcnf-config.sh render ($ts) from $CONFIG_KEY — do NOT edit.
# Per-mesh NON-SECRET identity; credentials come from the mesh secret store.
# mesh_id=$CFG_MESH_ID project=$CFG_PROJECT"

  # zone1-do: region + domain (+ golden is not used here).
  if [ -d "$tofu_dir/zone1-do" ]; then
    local region1="${CFG_REGIONS%%,*}"
    {
      printf '%s\n' "$hdr"
      printf 'region = "%s"\n' "$region1"
      printf 'domain = "%s"\n' "$CFG_DOMAIN"
    } >"$tofu_dir/zone1-do/mcnf-mesh.auto.tfvars"
    echo "wrote $tofu_dir/zone1-do/mcnf-mesh.auto.tfvars"
  fi

  # xen-xapi: the golden template name (the build farm clones it).
  if [ -d "$tofu_dir/xen-xapi" ]; then
    {
      printf '%s\n' "$hdr"
      printf 'golden_template_name = "%s"\n' "$CFG_GOLDEN"
    } >"$tofu_dir/xen-xapi/mcnf-mesh.auto.tfvars"
    echo "wrote $tofu_dir/xen-xapi/mcnf-mesh.auto.tfvars"
  fi

  # control-vm: mesh_id, the lighthouse roster + etcd anchors, golden template.
  if [ -d "$tofu_dir/control-vm" ]; then
    local lh_hcl anchors_hcl
    lh_hcl="$(_cfg_csv_to_hcl_list "$CFG_LIGHTHOUSES")"
    anchors_hcl="$lh_hcl"   # the founder etcd quorum == the lighthouse overlay roster
    {
      printf '%s\n' "$hdr"
      printf 'mesh_id = "%s"\n' "$CFG_MESH_ID"
      printf 'golden_template_name = "%s"\n' "$CFG_GOLDEN"
      printf 'lighthouse_overlay_ips  = %s\n' "$lh_hcl"
      printf 'etcd_anchor_overlay_ips = %s\n' "$anchors_hcl"
    } >"$tofu_dir/control-vm/mcnf-mesh.auto.tfvars"
    echo "wrote $tofu_dir/control-vm/mcnf-mesh.auto.tfvars"
  fi
}

# "a,b,c" -> '["a", "b", "c"]' (HCL list literal). Empty -> '[]'.
_cfg_csv_to_hcl_list() {
  local csv="$1" out="" tok
  [ -n "$csv" ] || { printf '[]'; return 0; }
  IFS=',' read -ra _toks <<<"$csv"
  for tok in "${_toks[@]}"; do
    tok="$(printf %s "$tok" | tr -d '[:space:]')"
    [ -n "$tok" ] || continue
    [ -n "$out" ] && out="$out, "
    out="$out\"$tok\""
  done
  printf '[%s]' "$out"
}

# Load the identity JSON from etcd into CFG_* globals (the single parse point).
_cfg_load_into_globals() {
  local doc
  doc="$(_cfg_get "$CONFIG_KEY")" || {
    echo "mcnf-config: $CONFIG_KEY not found — run 'mcnf-config.sh gen …' first" >&2
    exit 3
  }
  # Parse with python3 (tolerant; no jq dependency) into shell-eval lines.
  eval "$(printf '%s' "$doc" | python3 -c '
import sys, json, shlex
d = json.load(sys.stdin)
def g(k): return d.get(k, "") or ""
def csv(k):
    v = d.get(k, "")
    if isinstance(v, list): return ",".join(str(x) for x in v)
    return str(v or "")
print("CFG_MESH_ID="      + shlex.quote(g("mesh_id")))
print("CFG_PROJECT="      + shlex.quote(g("project")))
print("CFG_REGIONS="      + shlex.quote(csv("regions")))
print("CFG_LIGHTHOUSES="  + shlex.quote(csv("lighthouses")))
print("CFG_CONTROL_IP="   + shlex.quote(g("control_overlay_ip")))
print("CFG_DOMAIN="       + shlex.quote(g("domain")))
print("CFG_GOLDEN="       + shlex.quote(g("golden_template") or "MDE-VM-golden"))
')"
}

# Public source-able accessor: print one /mcnf/site/<field>. Used by gen-tfvars.sh
# and the orchestrator without re-implementing the parse.
mcnf_config_get_field() { # <field>
  _cfg_resolve_etcd
  _cfg_get "$SITE_PREFIX/$1"
}

# Public source-able accessor: load CFG_* into the caller's environment.
mcnf_config_load() { _cfg_resolve_etcd; _cfg_load_into_globals; }

# ── sourcing guard: when sourced (not executed) define funcs + return ──
# `${BASH_SOURCE[0]}` != `$0` ⇒ we were sourced; expose the accessors and stop.
if [ "${BASH_SOURCE[0]}" != "${0}" ]; then
  return 0 2>/dev/null || true
fi

# ── CLI dispatch ──
cmd="${1:-}"
case "$cmd" in
  gen)
    shift
    MESH_ID="${1:-}"; [ -n "$MESH_ID" ] || { echo "usage: gen <mesh-id> --project <p> --regions <r,...> --lighthouses <ip,...>" >&2; exit 2; }
    case "$MESH_ID" in --*) echo "gen: <mesh-id> must be the FIRST positional arg" >&2; exit 2;; esac
    shift
    PROJECT=""; REGIONS=""; LIGHTHOUSES=""; CONTROL_IP="${MCNF_CONTROL_IP:-}"
    DOMAIN=""; GOLDEN="${MCNF_GOLDEN_TEMPLATE:-MDE-VM-golden}"
    TOFU_DIR="$(cd "$_MCNF_CONFIG_HERE/../.." && pwd)/infra/tofu"; RENDER=1
    while [ $# -gt 0 ]; do case "$1" in
      --project)      PROJECT="$2"; shift 2;;
      --regions)      REGIONS="$2"; shift 2;;
      --lighthouses)  LIGHTHOUSES="$2"; shift 2;;
      --control-ip)   CONTROL_IP="$2"; shift 2;;
      --domain)       DOMAIN="$2"; shift 2;;
      --golden)       GOLDEN="$2"; shift 2;;
      --tofu-dir)     TOFU_DIR="$2"; shift 2;;
      --no-render)    RENDER=0; shift;;
      *) echo "gen: unknown arg '$1'" >&2; exit 2;;
    esac; done
    [ -n "$PROJECT" ]     || { echo "gen: --project <p> is required" >&2; exit 2; }
    [ -n "$REGIONS" ]     || { echo "gen: --regions <r,...> is required" >&2; exit 2; }
    [ -n "$LIGHTHOUSES" ] || { echo "gen: --lighthouses <ip,...> is required" >&2; exit 2; }
    [ -n "$DOMAIN" ]      || DOMAIN="matthewmackes.com"
    # control overlay IP is optional at found time (the VM mints it at join); if not
    # given we leave it empty in the doc and resolve it later via mackesd peers.

    _cfg_resolve_etcd

    # Build the one canonical JSON doc (regions/lighthouses as arrays). NO secrets.
    DOC="$(python3 -c '
import sys, json
mesh_id, project, regions, lighthouses, control_ip, domain, golden = sys.argv[1:8]
def lst(s): return [x.strip() for x in s.split(",") if x.strip()]
print(json.dumps({
    "mesh_id": mesh_id,
    "project": project,
    "regions": lst(regions),
    "lighthouses": lst(lighthouses),
    "control_overlay_ip": control_ip,
    "domain": domain,
    "golden_template": golden,
}, sort_keys=True))' "$MESH_ID" "$PROJECT" "$REGIONS" "$LIGHTHOUSES" "$CONTROL_IP" "$DOMAIN" "$GOLDEN")"

    _cfg_put "$CONFIG_KEY" "$DOC"
    # Flat per-field mirror under /mcnf/site/* (so consumers can get one field).
    _cfg_put "$SITE_PREFIX/mesh-id"            "$MESH_ID"
    _cfg_put "$SITE_PREFIX/project"            "$PROJECT"
    _cfg_put "$SITE_PREFIX/regions"            "$REGIONS"
    _cfg_put "$SITE_PREFIX/lighthouses"        "$LIGHTHOUSES"
    _cfg_put "$SITE_PREFIX/control-overlay-ip" "$CONTROL_IP"
    _cfg_put "$SITE_PREFIX/domain"             "$DOMAIN"
    _cfg_put "$SITE_PREFIX/golden-template"    "$GOLDEN"
    echo "wrote $CONFIG_KEY (mesh-id=$MESH_ID project=$PROJECT regions=$REGIONS)"

    if [ "$RENDER" -eq 1 ]; then
      _cfg_load_into_globals
      _cfg_render_roots "$TOFU_DIR"
    fi
    ;;

  render)
    shift
    TOFU_DIR="$(cd "$_MCNF_CONFIG_HERE/../.." && pwd)/infra/tofu"
    while [ $# -gt 0 ]; do case "$1" in
      --tofu-dir) TOFU_DIR="$2"; shift 2;;
      *) echo "render: unknown arg '$1'" >&2; exit 2;;
    esac; done
    _cfg_resolve_etcd
    _cfg_load_into_globals
    _cfg_render_roots "$TOFU_DIR"
    ;;

  get)
    shift
    _cfg_resolve_etcd
    if [ -n "${1:-}" ]; then
      _cfg_get "$SITE_PREFIX/$1" || { echo "mcnf-config: $SITE_PREFIX/$1 not found" >&2; exit 3; }
      echo
    else
      _cfg_get "$CONFIG_KEY" || { echo "mcnf-config: $CONFIG_KEY not found — run gen first" >&2; exit 3; }
      echo
    fi
    ;;

  selftest)
    # Offline self-test: mock etcd with a local dir; touches NO live store. Drives
    # the REAL gen/render/get arms (re-invoking $0 with the mock active) so the
    # production code paths are exercised. Asserts: (1) gen writes the doc + site
    # mirror with NO credentials, (2) render produces tfvars with the right
    # mesh-id/project/regions/golden, (3) a re-render from the doc alone is
    # byte-identical (idempotent), (4) a DIFFERENT mesh-id emits DIFFERENT values.
    MOCK_DIR="$(mktemp -d)"; export MOCK_DIR
    ETCD="mock://selftest"
    work="$(mktemp -d)"; tofu="$work/infra/tofu"
    mkdir -p "$tofu/zone1-do" "$tofu/xen-xapi" "$tofu/control-vm"
    fail=0
    pass() { printf '  PASS %s\n' "$1"; }
    bad()  { printf '  FAIL %s\n' "$1"; fail=1; }
    run() { env MCNF_CONFIG_SELFTEST=1 MOCK_DIR="$MOCK_DIR" "$@" >>"$work/run.log" 2>&1; }
    : >"$work/run.log"
    echo "mcnf-config selftest (mocked etcd at $MOCK_DIR — NO live store touched)"

    # --- gen mesh 4533's identity ---
    run bash "$0" gen 4533 --project mcnf-fam \
        --regions nyc3,fra1,sfo3 --lighthouses 10.42.0.4,10.42.0.5,10.42.0.6 \
        --control-ip 10.42.0.40 --domain matthewmackes.com --tofu-dir "$tofu"

    doc="$(env MCNF_CONFIG_SELFTEST=1 MOCK_DIR="$MOCK_DIR" bash "$0" get 2>/dev/null || true)"
    case "$doc" in *'"mesh_id": "4533"'*) pass "gen wrote the identity doc" ;; *) bad "identity doc missing/wrong: $doc" ;; esac

    # site mirror
    m="$(env MCNF_CONFIG_SELFTEST=1 MOCK_DIR="$MOCK_DIR" bash "$0" get mesh-id 2>/dev/null || true)"
    [ "$m" = "4533" ] && pass "site mirror /mcnf/site/mesh-id = 4533" || bad "site mesh-id = '$m' (want 4533)"

    # tfvars content
    zv="$tofu/zone1-do/mcnf-mesh.auto.tfvars"
    xv="$tofu/xen-xapi/mcnf-mesh.auto.tfvars"
    cv="$tofu/control-vm/mcnf-mesh.auto.tfvars"
    [ -f "$zv" ] && grep -q 'region = "nyc3"' "$zv" && grep -q 'domain = "matthewmackes.com"' "$zv" \
      && pass "zone1-do tfvars carries region+domain" || bad "zone1-do tfvars wrong: $(cat "$zv" 2>/dev/null)"
    [ -f "$xv" ] && grep -q 'golden_template_name = "MDE-VM-golden"' "$xv" \
      && pass "xen-xapi tfvars carries the canonical golden template" || bad "xen-xapi golden wrong: $(cat "$xv" 2>/dev/null)"
    [ -f "$cv" ] && grep -q 'mesh_id = "4533"' "$cv" && grep -q '10.42.0.4' "$cv" \
      && pass "control-vm tfvars carries mesh_id + lighthouse roster" || bad "control-vm tfvars wrong: $(cat "$cv" 2>/dev/null)"

    # NO credentials in any generated file (no age key, no token-shaped value).
    if grep -RqiE 'AGE-SECRET-KEY|do[-_]token|password|secret[-_]key|xapi[-_]password' "$tofu"/*/*.auto.tfvars 2>/dev/null; then
      bad "a credential-shaped value leaked into the generated tfvars"
    else
      pass "no credential appears in any generated tfvars"
    fi

    # --- render again from the doc alone → byte-identical (idempotent) ---
    cp "$zv" "$work/zv.1"; cp "$xv" "$work/xv.1"; cp "$cv" "$work/cv.1"
    run bash "$0" render --tofu-dir "$tofu"
    # The header carries a timestamp, so compare with the timestamp line stripped.
    strip() { grep -v '^# GENERATED by' "$1"; }
    if diff <(strip "$work/zv.1") <(strip "$zv") >/dev/null \
       && diff <(strip "$work/xv.1") <(strip "$xv") >/dev/null \
       && diff <(strip "$work/cv.1") <(strip "$cv") >/dev/null; then
      pass "re-render from the etcd doc is identical (idempotent)"
    else
      bad "re-render differs from the first render"
    fi

    # --- a DIFFERENT mesh-id emits DIFFERENT values ---
    MOCK2="$(mktemp -d)"
    env MCNF_CONFIG_SELFTEST=1 MOCK_DIR="$MOCK2" bash "$0" gen 9001 --project other-fam \
        --regions ams3 --lighthouses 10.99.0.4 --tofu-dir "$tofu" >>"$work/run.log" 2>&1
    grep -q 'region = "ams3"' "$zv" && grep -q 'mesh_id = "9001"' "$cv" \
      && pass "a different mesh-id emits different tfvars" || bad "second mesh did not change tfvars"
    rm -rf "$MOCK2"

    # --- NO secret value / private key in the run log ---
    if grep -qE 'AGE-SECRET-KEY' "$work/run.log"; then bad "a private key leaked into the log"; else pass "no private key in any logged output"; fi

    rm -rf "$MOCK_DIR" "$work"
    if [ "$fail" -eq 0 ]; then echo "selftest: ALL PASS"; else echo "selftest: FAILURES" >&2; fi
    exit "$fail"
    ;;

  -h|--help|"")
    sed -n '2,46p' "$0" | sed 's/^# \{0,1\}//'
    [ "$cmd" = "" ] && exit 2 || exit 0
    ;;

  *)
    echo "mcnf-config: unknown command '$cmd' (gen|render|get|selftest)" >&2
    exit 2
    ;;
esac
